name: Actions Ecosystem Bump Calver
description: Bump a calver version up.
author: juusopiikkila
inputs:
  current_version:
    description: The current version.
    required: true
outputs:
  new_version:
    description: The bumped calver version.
runs:
  using: node16
  main: dist/index.js
branding:
  icon: bookmark
  color: white
